<a href="https://colab.research.google.com/github/JaTest1/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
np.__version__

'1.23.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

In [ ]:
x = np.array([[1, 2], [-3, 1]])
print(x)

[[ 1  2]
 [-3  1]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1, 2,4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

In [ ]:
x= np.array(
    [[[4, 3, 1],
     [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 1]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(3, 2, 3)

In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
A = np.array([1.0, 2.3, 3.3], dtype='int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 330], dtype=np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 120, 330], dtype=np.uint8)
A.dtype

dtype('uint8')

In [3]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
np.full(shape=(3,3), fill_value = 4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [14]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [15]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [16]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [20]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [4]:
A = np.array([3,1,4,2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)


[3 1 4 2]
[ 3 -1  3  2]


In [5]:
A + B

array([6, 0, 7, 4])

In [6]:
A - B

array([0, 2, 1, 0])

In [7]:
A * B

array([ 9, -1, 12,  4])

In [10]:
2 * A

array([6, 2, 8, 4])

In [8]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [12]:
np.add(A, B)

array([6, 0, 7, 4])

In [13]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [14]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [15]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [9]:
A + 3

array([6, 4, 7, 5])

In [11]:
A + 3*B

array([12, -2, 13,  8])

In [19]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [18]:
X * Y

array([[6, 0],
       [2, 0]])

In [20]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [21]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [23]:
X@Y

array([[  3,   6],
       [-12,   0]])

In [ ]:
np.random.seed(0)

In [25]:
np.random.randn()

-0.8083863245193358

In [27]:
np.random.randn(10)

array([-0.07356294, -0.13340239, -0.10603975,  0.52617118,  0.26581351,
       -0.70642621, -0.09167699, -1.59868772, -0.36860691, -1.01733644])

In [28]:
np.random.randn(10, 4)

array([[ 0.42713095, -0.10401405, -0.30526445, -0.77090743],
       [-1.04422294, -1.3446134 ,  0.56174385,  0.09134382],
       [ 0.15825727, -0.09330068,  0.19186927,  1.02834109],
       [-1.23558685, -0.58612047,  0.97930641, -0.28971485],
       [ 1.50141107, -1.66049714,  0.30663559,  1.26622523],
       [ 0.64653482,  0.78831933, -0.25591605,  0.84707244],
       [ 0.2503778 , -0.10299745,  1.78107473, -2.47910279],
       [-0.06878557,  1.39849143,  0.30573305, -1.59660091],
       [-0.40774286,  0.11654834,  0.21889959, -1.41766116],
       [-1.66347695,  0.76360243, -0.85407317,  0.34694404]])

In [30]:
np.random.rand()

0.6737920812483952

In [31]:
np.random.rand(10)

array([0.78555028, 0.38345692, 0.56953394, 0.93220776, 0.19416271,
       0.9047235 , 0.20346052, 0.66765702, 0.35559142, 0.16481218])

In [32]:
np.random.rand(10, 2)

array([[0.67750007, 0.4974584 ],
       [0.13883602, 0.26734172],
       [0.26837113, 0.36752503],
       [0.65548821, 0.92492607],
       [0.91334781, 0.54231678],
       [0.33843332, 0.59840833],
       [0.99720217, 0.70597141],
       [0.42148556, 0.94066947],
       [0.2359361 , 0.59199479],
       [0.67102904, 0.54365328]])

In [34]:
np.random.randint(10)

2

In [36]:
np.random.randint(low=10, high=101)

50

In [37]:
np.random.randint(low=10, high=101, size=10)

array([44, 61, 41, 79, 48, 76, 56, 58, 29, 36])

In [39]:
np.random.choice([4, 2, 1, 3, 5])

1

In [40]:
np.random.choice(['python', 'java', 'sql'])

'java'

In [43]:
data=np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.random.shuffle(data)

In [49]:
data

array([8, 3, 2, 4, 9, 7, 5, 6, 1, 0])

In [50]:
np.exp(1)

2.718281828459045

In [51]:
np.exp(3)

20.085536923187668

In [52]:
np.sqrt(9)

3.0

In [54]:
np.all([2, 3,1])

True

In [56]:
np.all([2, 3,0])

False

In [57]:
np.any([1, 2, 3])

True

In [58]:
np.any([0, 0, 0])

False

In [62]:
A = np.random.rand(5)
A

array([0.50994133, 0.06708591, 0.25033637, 0.34961285, 0.7777949 ])

In [66]:
np.argmax(A)

4

In [64]:
A[np.argmax(A)]

0.7777948962560756

In [67]:
np.argmin(A)

1

In [68]:
A[np.argmin(A)]

0.06708590911601842

In [69]:
np.argsort(A)

array([1, 2, 3, 0, 4])

In [70]:
np.max(A)

0.7777948962560756

In [71]:
np.min(A)

0.06708590911601842

In [72]:
np.mean(A)

0.390954271746612

In [73]:
np.median(A)

0.349612852530259

In [74]:
np.std(A)

0.24090529718474216

In [77]:
A =np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [78]:
A[2]

2

In [79]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [81]:
A[:2]

array([0, 1])

In [82]:
A[[0,2]]

array([0, 2])

In [83]:
A[-1]

19

In [85]:
A[10:15]

array([10, 11, 12, 13, 14])

In [87]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [89]:
A[0]

array([0, 1, 2, 3, 4])

In [90]:
A[1]

array([5, 6, 7, 8, 9])

In [91]:
A[:, 0]

array([ 0,  5, 10, 15])

In [92]:
A[:, -1]

array([ 4,  9, 14, 19])

In [93]:
A[:, -2]

array([ 3,  8, 13, 18])

In [94]:
A[1,1]

6

In [95]:
A[1,3]

8

In [97]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [100]:
A[1,2]

7

In [101]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [102]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [103]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [105]:
for row in A:
  print(row[0])

0
5
10
15


In [106]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [107]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [108]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [109]:
A.shape

(4, 5)

In [110]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [111]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [112]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [115]:
A = np.arange(start = -10, stop = 10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [116]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [117]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [119]:
np.bitwise_and(A>-5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [120]:
A[np.bitwise_and(A>-5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [121]:
np.bitwise_or(A<-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])