<a href="https://colab.research.google.com/github/JaTest1/data-science-bootcamp/blob/main/01_numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.23.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [5]:
x = np.array([1, 3])
x

array([1, 3])

In [6]:
print(x)

[1 3]


In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [14]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [15]:
x.dtype

dtype('float64')

In [18]:
x = np.array([[1, 2], [-3, 1]])
print(x)

[[ 1  2]
 [-3  1]]


In [19]:
x.ndim

2

In [20]:
x.shape

(2, 2)

In [22]:
x = np.array([[1, 2,4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [23]:
x.shape

(2, 3)

In [28]:
x= np.array(
    [[[4, 3, 1],
     [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 1]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 1]]])

In [29]:
x.ndim

3

In [30]:
x.shape

(3, 2, 3)

In [32]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [40]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [36]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [38]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [43]:
A = np.array([1.0, 2.3, 3.3], dtype='int')
A.dtype

dtype('int64')

In [44]:
A

array([1, 2, 3])

In [45]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [47]:
A = np.array([24, 120, 330], dtype=np.int8)
A.dtype

dtype('int8')

In [48]:
A = np.array([24, 120, 330], dtype=np.uint8)
A.dtype

dtype('uint8')