<a href="https://colab.research.google.com/github/JaTest1/data-science-bootcamp/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1)

4.123105625617661

In [ ]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [ ]:
p = np.array([3,0])
q = np.array([0, 4])
np.linalg.norm(p-q)

5.0

In [ ]:
p = np.array([3,0,1])
q = np.array([0,4,2])
np.linalg.norm(p-q)

5.0990195135927845

In [4]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [11]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

In [6]:
Z.shape

(2, 1)

In [10]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [12]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])